name: toku_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  audioplayers: ^6.1.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0 
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter:
  uses-material-design: true
    
  fonts:
    - family: ADLaM Display
      fonts:
        - asset: assets/fonts/ADLaMDisplay-Regular.ttf
       
    

  assets:
    - assets/images/numbers/
    - assets/images/family_members/
    - assets/images/colors/
    - assets/sounds/numbers/
    - assets/sounds/family_members/
    - assets/sounds/colors/
    - assets/sounds/phrases/
    - assets/
